wordList = { 
  "것" : "A thing or object",
  "하다 (1)" : "To do",
  "있다" : "To be",
  "수" : "way, method",
  "나" : "I",
  "없다" : "without, absent",
  "않다" : "To not be/do",
  "사람" : "Person",
  "우리" : "we/our",
  "그" : "He",
  "아니다" : "To not be",
  "보다 (1)" : "To try",
  "거" : "That thing",
  "보다 (2)" : "To see",
  "같다" : "To be similar",
  "주다" : "To give/do for a person",
  "대하다" : "To face/confront",
  "가다" : "To go",
  "년" : "Year",
  "한" : "One/single",
  "말" : "speech, language, words",
  "일 (1)" : "Work",
  "이" : "A man/woman",
  "말하다" : "To say",
  "위하다" : "To do for",
  "그러나" : "However",
  "오다" : "To come",
  "알다" : "To know",
  "씨" : "Mr./Ms.",
  "그렇다" : "That is right",
  "크다" : "To be big/large",
  "일 (2)" : "One day",
  "사회" : "society, culture",
  "많다" : "many, much",
  "안" : "not",
  "좋다" : "To be good",
  "더" : "More",
  "받다" : "To receive",
  "그것" : "That thing",
  "집" : "house, home",
  "나오다" : "To come out",
  "그리고" : "And then",
  "문제" : "problem, question",
  "그런" : "Such a",
  "살다" : "To live",
  "저" : "That",
  "못하다" : "To be impossible",
  "생각하다" : "To think",
  "모르다" : "To not know"
}

